stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - data_given/ds_salaries.csv
    outs:
      - data/raw/ds_salaries.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/ds_salaries.csv
    outs:
      - data/processed/train_ds_salaries.csv
      - data/processed/test_ds_salaries.csv